# Generated by Django 4.0 on 2021-12-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_measurement_data_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='data_sensor',
            new_name='sensor_data',
        ),
    ]
